// libs/forms-angular/src/lib/fields/field-birth-certificate.component.ts
import { Component, computed, effect, signal } from '@angular/core'
import { ReactiveFormsModule } from '@angular/forms'
import { normalizeBirthCertificate, validateBirthCertificate } from '@letar/forms-core/validators/ru'
import { FieldBase } from '../core/field-base'

/**
 * Свидетельство о рождении — Angular-эквивалент `FieldBirthCertificate` (`@letar/forms-vue`).
 * НЕ наследует `DocumentFieldBase` — как и Vue-версия, БЕЗ структурной маски (римская часть
 * серии переменной длины, 1-5 знаков; структурная маска дала бы ложный отказ). Свободный ввод —
 * поэтому обычный `[formControl]`-биндинг (как у `FieldStringComponent`) достаточен, движок
 * масок не нужен, а значит нет и причины отказываться от `ControlValueAccessor` (в отличие от
 * `DocumentFieldBase`, см. её комментарий "Почему НЕ `[formControl]`").
 *
 * Нормализация гомоглифов (`|||`→`III`, позиционные X/Х) и разделителей — на `blur`, не на
 * каждый символ, 1-в-1 порт `field-birth-certificate.ts` (Vue).
 */
@Component({
  selector: 'letar-field-birth-certificate',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    @if (control(); as ctrl) {
      <div class="letar-field">
        <label [for]="name">{{ resolvedLabel() }}{{ isRequired() ? ' *' : '' }}</label>
        <input
          [id]="name"
          [formControl]="ctrl"
          [placeholder]="resolvedPlaceholder() ?? 'II-МЮ № 123456'"
          type="text"
          class="letar-field__control"
          (blur)="onBlur()"
        />
        @if (hasFormatError()) {
          <span class="letar-field__error" role="alert">{{ displayErrorMessage() }}</span>
        }
      </div>
    }
  `,
})
export class FieldBirthCertificateComponent extends FieldBase {
  /** Собственная ошибка формата (независимо от Zod-схемы приложения — тот же принцип
   * defence-in-depth, что у документных полей, см. `DocumentFieldBase`). */
  private readonly formatErrorMessage = signal('')
  readonly hasFormatError = computed(() => this.hasError() || this.formatErrorMessage().length > 0)
  readonly displayErrorMessage = computed(() => this.formatErrorMessage() || this.errorMessage())

  constructor() {
    super()
    effect((onCleanup) => {
      const ctrl = this.control()
      if (!ctrl) {
        return
      }
      const sync = () => {
        const raw = typeof ctrl.value === 'string' ? ctrl.value : ''
        this.formatErrorMessage.set(
          raw && !validateBirthCertificate(raw)
            ? 'Формат: римская часть-две буквы № шесть цифр (например, II-МЮ № 123456)'
            : '',
        )
      }
      sync()
      const subscription = ctrl.valueChanges.subscribe(sync)
      onCleanup(() => subscription.unsubscribe())
    })
  }

  protected onBlur(): void {
    const ctrl = this.control()
    if (!ctrl) {
      return
    }
    const raw = typeof ctrl.value === 'string' ? ctrl.value : ''
    if (raw) {
      ctrl.setValue(normalizeBirthCertificate(raw))
    }
    ctrl.markAsTouched()
  }
}

// libs/forms/src/lib/declarative/form-fields/document/field-birth-certificate.tsx
'use client'

import { Field, Icon, Input, InputGroup } from '@chakra-ui/react'
import { normalizeBirthCertificate, validateBirthCertificate } from '@letar/forms-core/validators/ru'
import { useStore } from '@tanstack/react-form'
import type { ReactElement } from 'react'
import { LuBaby } from 'react-icons/lu'
import type { FieldTooltipMeta } from '../../types'
import { createField, FieldError, FieldLabel } from '../base'

export interface BirthCertificateFieldProps {
  name?: string
  label?: string
  helperText?: string
  required?: boolean
  disabled?: boolean
  tooltip?: FieldTooltipMeta
}

interface BirthCertificateFieldState {
  rawValue: string
}

/**
 * Form.Document.BirthCertificate — свидетельство о рождении.
 *
 * БЕЗ маски (MASK_ENGINE.md §7.1, критерий §5.3) — римская часть серии переменной длины
 * (1-5 знаков), структурная маска дала бы ложный отказ. Свободный ввод: пользователь печатает
 * как удобно, нормализация гомоглифов (`|||`→`III`, позиционные X/Х) и разделителей происходит
 * на blur — не на каждый символ, иначе неоконченная римская часть искажается раньше времени.
 */
export const FieldBirthCertificate = createField<BirthCertificateFieldProps, string, BirthCertificateFieldState>({
  displayName: 'FieldBirthCertificate',

  useFieldState: (_props, _resolved, context) => {
    const { form, fullPath } = context
    const rawValue = (useStore(form.store, () => form.getFieldValue(fullPath)) as string | undefined) ?? ''
    return { rawValue }
  },

  render: ({ field, resolved, hasError, errorMessage, fieldState }): ReactElement => {
    const customError = fieldState.rawValue && !validateBirthCertificate(fieldState.rawValue)
      ? 'Формат: римская часть-две буквы № шесть цифр (например, II-МЮ № 123456)'
      : undefined
    const showError = hasError || !!customError
    const displayError = customError ?? errorMessage

    return (
      <Field.Root invalid={showError} required={resolved.required} disabled={resolved.disabled}>
        <FieldLabel label={resolved.label} tooltip={resolved.tooltip} required={resolved.required} />

        <InputGroup
          startElement={
            <Icon color="fg.muted">
              <LuBaby />
            </Icon>
          }
        >
          <Input
            value={fieldState.rawValue}
            onChange={(event) => field.handleChange(event.target.value)}
            onBlur={() => {
              if (fieldState.rawValue) {
                field.handleChange(normalizeBirthCertificate(fieldState.rawValue))
              }
              field.handleBlur()
            }}
            placeholder="II-МЮ № 123456"
          />
        </InputGroup>

        <FieldError hasError={showError} errorMessage={displayError} helperText={resolved.helperText} />
      </Field.Root>
    )
  },
})
