// libs/forms-angular/src/lib/fields/field-foreign-passport.component.ts
import { Component, Input } from '@angular/core'
import { validateForeignPassport } from '@letar/forms-core/validators/ru'
import { DOCUMENT_FIELD_TEMPLATE, DocumentFieldBase } from '../core/document-field-base'

/** Загранпаспорт (99 9999999, серия 2 + номер 7) — Angular-эквивалент `FieldForeignPassport`
 * (`@letar/forms-vue`). */
@Component({
  selector: 'letar-field-foreign-passport',
  standalone: true,
  template: DOCUMENT_FIELD_TEMPLATE,
})
export class FieldForeignPassportComponent extends DocumentFieldBase {
  readonly mask = '99 9999999'

  @Input()
  override placeholder = '75 0123456'

  protected validateDocument(value: string): string | undefined {
    const digits = value.replace(/\D/g, '')
    return validateForeignPassport(digits) ? undefined : 'Загранпаспорт должен содержать 9 цифр (серия + номер)'
  }
}

// libs/forms/src/lib/declarative/form-fields/document/field-foreign-passport.tsx
'use client'

import { validateForeignPassport } from '@letar/forms-core/validators/ru'
import { LuPlane } from 'react-icons/lu'
import { createDocumentField } from './document-field-base'

/** Form.Document.ForeignPassport — загранпаспорт (99 9999999, серия 2 + номер 7) */
export const FieldForeignPassport = createDocumentField({
  displayName: 'FieldForeignPassport',
  mask: '99 9999999',
  placeholder: '75 0123456',
  icon: LuPlane,
  validate: (value) => {
    const digits = value.replace(/\D/g, '')
    if (!digits) {
      return undefined
    }
    return validateForeignPassport(digits) ? undefined : 'Загранпаспорт должен содержать 9 цифр (серия + номер)'
  },
})
