// libs/forms-angular/src/lib/fields/field-listbox.component.ts
import { Component, effect, Input, signal } from '@angular/core'
import { getOptionLabel, groupOptions } from '@letar/forms-core/uikit'
import { FieldBase } from '../core/field-base'

export interface ListboxOption {
  value: string
  label: string
  disabled?: boolean
  group?: string
}

/**
 * Все опции видны сразу (не выпадающий список) — Angular-эквивалент `FieldListbox`
 * (`@letar/forms-vue`). `string | string[]` в зависимости от `selectionMode`, группировка через
 * `groupOptions`/`getOptionLabel` из `@letar/forms-core/uikit` (то же framework-free ядро, что и
 * Vue-версия — без единой правки под Angular).
 *
 * Контрол держит примитив/массив целиком (тот же принцип, что `DateRange`/`Schedule`, Stage D) —
 * кнопки-опции не `[formControl]`-совместимы (нет нативного value-accessor для кастомного
 * `role="option"`), поэтому свой сигнал `valueArray`, синхронизируемый через `effect()` +
 * `ctrl.events.subscribe()`, и ручной `ctrl.setValue()` по клику.
 */
@Component({
  selector: 'letar-field-listbox',
  standalone: true,
  template: `
    @if (control(); as ctrl) {
      <div class="letar-field" [attr.data-field-name]="name">
        @if (resolvedLabel()) {
          <span class="letar-field__label">{{ resolvedLabel() }}{{ isRequired() ? ' *' : '' }}</span>
        }
        <div
          role="listbox"
          [attr.aria-multiselectable]="selectionMode === 'multiple'"
          [attr.data-field-name]="name"
          class="letar-field__listbox"
        >
          @for (group of groupedOptions(); track group.name) {
            @if (group.name) {
              <div class="letar-field__listbox-group">{{ group.name }}</div>
            }
            @for (option of group.options; track option.value) {
              <button
                type="button"
                role="option"
                class="letar-field__listbox-option"
                [attr.aria-selected]="isSelected(option.value)"
                [attr.data-selected]="isSelected(option.value) || null"
                [disabled]="option.disabled"
                (click)="toggle(ctrl, option.value)"
              >{{ getOptionLabel(option) }}</button>
            }
          }
        </div>
        @if (hasError()) {
          <span class="letar-field__error" role="alert">{{ errorMessage() }}</span>
        }
      </div>
    }
  `,
})
export class FieldListboxComponent extends FieldBase {
  @Input({ required: true })
  options: ListboxOption[] = []
  @Input()
  selectionMode: 'single' | 'multiple' = 'single'

  readonly valueArray = signal<string[]>([])

  constructor() {
    super()
    effect((onCleanup) => {
      const ctrl = this.control()
      if (!ctrl) {
        return
      }
      const sync = () => {
        const value = ctrl.value as string | string[] | undefined
        this.valueArray.set(Array.isArray(value) ? value : value ? [value] : [])
      }
      sync()
      const subscription = ctrl.events.subscribe(sync)
      onCleanup(() => subscription.unsubscribe())
    })
  }

  groupedOptions(): { name: string; options: ListboxOption[] }[] {
    const groups = groupOptions(this.options)
    if (!groups) {
      return [{ name: '', options: this.options }]
    }
    return Array.from(groups.entries()).map(([name, options]) => ({ name: name || '', options }))
  }

  getOptionLabel(option: ListboxOption): string {
    return getOptionLabel(option)
  }

  isSelected(value: string): boolean {
    return this.valueArray().includes(value)
  }

  toggle(ctrl: { setValue: (value: string | string[]) => void; markAsTouched: () => void }, value: string): void {
    if (this.selectionMode === 'single') {
      ctrl.setValue(this.valueArray()[0] === value ? '' : value)
    } else {
      const current = this.valueArray()
      const next = current.includes(value) ? current.filter((v) => v !== value) : [...current, value]
      ctrl.setValue(next)
    }
    ctrl.markAsTouched()
  }
}

// libs/forms-shadcn/src/lib/fields/field-listbox.tsx
'use client'

import { getOptionLabel, groupOptions } from '@letar/forms-core/uikit'
import type { ReactElement } from 'react'
import { createField, FieldWrapper } from '../uikit/primitives'
import { cn } from '../utils/cn'
import type { ListboxFieldProps, ListboxOption } from './types'

function optionButtonClass(selected: boolean, disabled: boolean | undefined): string {
  return cn(
    'w-full rounded-md px-3 py-2 text-left text-sm outline-none',
    selected ? 'bg-primary text-primary-foreground' : 'hover:bg-accent hover:text-accent-foreground',
    disabled && 'pointer-events-none opacity-50',
  )
}

/**
 * Form.Field.Listbox — shadcn-скин.
 *
 * В отличие от Select/Combobox все опции видны сразу — список кнопок с `aria-selected`, не
 * выпадающий список. Нет отдельного Radix-примитива для listbox — обычные кнопки, тот же класс
 * стилей, что у пунктов `shadcnUIKit.Combobox`. Группировка через `groupOptions` из
 * `@letar/forms-core/uikit` (framework-free, не требует адаптера).
 */
export const FieldListbox = createField<ListboxFieldProps, string | string[]>({
  displayName: 'FieldListbox',

  render: ({ field, fullPath, resolved, hasError, errorMessage, componentProps }): ReactElement => {
    const { options, selectionMode = 'single' } = componentProps
    const currentValue = field.state.value as string | string[] | undefined
    const valueArray: string[] = Array.isArray(currentValue) ? currentValue : currentValue ? [currentValue] : []

    const toggle = (optionValue: string) => {
      if (selectionMode === 'single') {
        field.handleChange(valueArray[0] === optionValue ? '' : optionValue)
        return
      }
      const next = valueArray.includes(optionValue)
        ? valueArray.filter((v) => v !== optionValue)
        : [...valueArray, optionValue]
      field.handleChange(next)
    }

    const groups = groupOptions(options)

    const renderOption = (opt: ListboxOption) => {
      const optValue = String(opt.value)
      const selected = valueArray.includes(optValue)
      return (
        <button
          key={optValue}
          type="button"
          role="option"
          aria-selected={selected}
          disabled={opt.disabled || resolved.disabled}
          onClick={() => toggle(optValue)}
          className={optionButtonClass(selected, opt.disabled)}
        >
          {getOptionLabel(opt)}
        </button>
      )
    }

    return (
      <FieldWrapper resolved={resolved} hasError={hasError} errorMessage={errorMessage} fullPath={fullPath}>
        <div
          role="listbox"
          aria-multiselectable={selectionMode === 'multiple'}
          data-field-name={fullPath}
          className="space-y-1"
        >
          {groups
            ? Array.from(groups.entries()).map(([groupName, groupOpts]) => (
              <div key={groupName}>
                {groupName && <div className="text-muted-foreground px-3 py-1 text-xs font-medium">{groupName}</div>}
                {groupOpts.map(renderOption)}
              </div>
            ))
            : options.map(renderOption)}
        </div>
      </FieldWrapper>
    )
  },
})
