// libs/forms-angular/src/lib/fields/field-bank-account.component.ts
import { Component, Input } from '@angular/core'
import { DOCUMENT_FIELD_TEMPLATE, DocumentFieldBase } from '../core/document-field-base'

/** Расчётный счёт (20 цифр) — Angular-эквивалент `FieldBankAccount` (`@letar/forms-vue`). */
@Component({
  selector: 'letar-field-bank-account',
  standalone: true,
  template: DOCUMENT_FIELD_TEMPLATE,
})
export class FieldBankAccountComponent extends DocumentFieldBase {
  readonly mask = '99999999999999999999'

  @Input()
  override placeholder = '40702810038000000001'

  protected validateDocument(value: string): string | undefined {
    const digits = value.replace(/\D/g, '')
    if (digits.length !== 20) {
      return 'Расчётный счёт должен содержать 20 цифр'
    }
    return undefined
  }
}

// libs/forms-shadcn/src/lib/fields/field-bank-account.tsx
'use client'

import { Landmark } from 'lucide-react'
import { createDocumentField } from './document-field-base'

/** Form.Field.BankAccount (shadcn) — поле расчётного счёта (20 цифр) */
export const FieldBankAccount = createDocumentField({
  displayName: 'FieldBankAccount',
  mask: '99999999999999999999',
  placeholder: '40702810038000000001',
  icon: <Landmark />,
  validate: (value) => {
    const digits = value.replace(/\D/g, '')
    if (!digits) {
      return undefined
    }
    if (digits.length !== 20) {
      return 'Расчётный счёт должен содержать 20 цифр'
    }
    return undefined
  },
})

/** Form.Field.CorrAccount (shadcn) — поле корр. счёта (20 цифр, начинается с 301) */
export const FieldCorrAccount = createDocumentField({
  displayName: 'FieldCorrAccount',
  mask: '99999999999999999999',
  placeholder: '30101810400000000225',
  icon: <Landmark />,
  validate: (value) => {
    const digits = value.replace(/\D/g, '')
    if (!digits) {
      return undefined
    }
    if (digits.length !== 20) {
      return 'Корр. счёт должен содержать 20 цифр'
    }
    if (!digits.startsWith('301')) {
      return 'Корр. счёт должен начинаться с "301"'
    }
    return undefined
  },
})
